---
title: "shotspottter"
author: "Niel Schrage"
date: "4/20/2019"
output: html_document
---



```{r setup, include=FALSE, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# Load Packages

library(tigris)
library(ggplot2)
library(purrr)
library(tidyverse)
library(fs)
library(sf)
library(lubridate)
library(ggmap)
library(ggplot2)
library(mapproj)
library(ggthemes)
library(viridis)
library(scales)
library(gganimate)
library(shiny)
library(giphyr)


# set up functions 
```

# Introduction to the Project

## Looking at Data 

```{r read in data, include=FALSE}

# Read in Data 

shotspotter <- read_csv("http://justicetechlab.org/wp-content/uploads/2018/05/San_Francisco_ShotSpotter.csv", col_types = 
  cols(
  Type = col_character(),
  ID = col_double(),
  Date = col_character(),
  Time = col_time(format = ""),
  Rnds = col_double(),
  Beat = col_logical(),
  DISPO = col_logical(),
  `returned address` = col_character(),
  Latitude = col_double(),
  Longitude = col_double()
)) 
```

```{r shape files + editing, include=FALSE}
san_francisco <- places("ca", class = "sf", cb = TRUE) %>% 
  filter(NAME == "San Francisco")

shotspotter <- shotspotter %>% 
  
  mutate(Rnds = as.numeric(Rnds)) %>%
  
  mutate(Hours = hour(Time)) %>% 
  
  mutate(Date = dmy(Date)) %>% 
  
  mutate(Month = month(Date)) %>% 
  
  mutate(Week = week(Date)) %>% 
  
  filter(Latitude > 37.71) %>% 
  
  filter(Rnds < 100) %>% 
  
  # turn locations into sf object in order to graph 
  st_as_sf(coords = c("Longitude", "Latitude"), crs = st_crs(san_francisco))
```


# Plot 1
```{r set up plot, echo=FALSE, warning=FALSE, results="asis"}
# set up plot

p1 <- ggplot(data = san_francisco) + 
  
  # setting up san francisco backdrop
  
  geom_sf(fill = "cornsilk") + 
  
  # putting in layer with shop
  
  geom_sf(data = shotspotter, aes(size = Rnds, color = Hours), show.legend = FALSE) +
  
  scale_color_viridis() + 
  
  # formatting graph, by scaling and setting limits.
  
  coord_sf(xlim = c(-122.52, -122.35), ylim = c(37.7, 37.82)) +
  
  #scale_x_continuous(limits = c(-122.52, -122.35)) +
  
  #scale_y_continuous(limits = c(37.7, 37.85)) +
  
  xlab("Longitude") + ylab("Latitude") +
  
  ggtitle("ShotSpotter SF Data Collected on {closest_state}", subtitle = "Size: # of Rounds Fired, Color: Time of Day (lighter = earlier)") +
    
  labs(size = "Rounds Fired", color = "Hour of the Day", caption = "Source: Justice Tech Lab") +
  
  guides(size=guide_legend(title=NULL), color=guide_legend(title=NULL)) +

  theme_map() + 
  
  theme_tufte() + 

  transition_states(Date, state_length = 106)



```

```{r}
renderPlot({ 
  plot(p1) 
}, outputArgs = list(width = "75%", 
                     height = "250px")
)
```


# Plot 2
```{r plot 2, echo=FALSE, results=}
p2 <- ggplot(data = san_francisco) + 
  
  # setting up san francisco backdrop
  
  geom_sf(fill = "cornsilk") + 
  
  # putting in layer with shop
  
  geom_sf(data = shotspotter, aes(size = Rnds, color = Month), show.legend = FALSE) +
  
  scale_color_viridis() + 
  
  # formatting graph, by scaling and setting limits.
  
  coord_sf(xlim = c(-122.52, -122.35), ylim = c(37.7, 37.82)) +
  
  #scale_x_continuous(limits = c(-122.52, -122.35)) +
  
  #scale_y_continuous(limits = c(37.7, 37.85)) +
  
  xlab("Longitude") + ylab("Latitude") +
  
  ggtitle("ShotSpotter SF Data Collected on {closest_state}", subtitle = "Size: # of Rounds Fired, Color: Month (lighter = earlier in year)") +
    
  labs(size = "Rounds Fired", color = "Hour of the Day", caption = "Source: Justice Tech Lab") +
  
  guides(size=guide_legend(title=NULL), color=guide_legend(title=NULL)) +

  theme_map() + 
  
  theme_tufte() + 

  transition_states(Year, state_length = 10, transition_length = 5)

add_gifs("test.gif")

```


# Lots of Shots
```{r plot 3}
p3 <- shotspotter %>% 
  
  filter(Rnds > 50) %>% 

  ggplot(data = san_francisco) + 
  
  # setting up san francisco backdrop
  
  geom_sf(fill = "cornsilk") + 
  
  # putting in layer with shop
  
  geom_sf(data = shotspotter, aes(size = Rnds, color = Year), show.legend = FALSE) +
  
  scale_color_viridis() + 
  
  # formatting graph, by scaling and setting limits.
  
  coord_sf(xlim = c(-122.52, -122.35), ylim = c(37.7, 37.82)) +
  
  #scale_x_continuous(limits = c(-122.52, -122.35)) +
  
  #scale_y_continuous(limits = c(37.7, 37.85)) +
  
  xlab("Longitude") + ylab("Latitude") +
  
  ggtitle("ShotSpotter SF Data Collected on {closest_state}", subtitle = "Size: # of Rounds Fired, Color: Year") +
    
  labs(size = "Rounds Fired", color = "Hour of the Day", caption = "Source: Justice Tech Lab") +
  
  guides(size=guide_legend(title=NULL), color=guide_legend(title=NULL)) +

  theme_map() + 
  
  theme_tufte() + 

  transition_states(Year, state_length = 10, transition_length = 5)


```

